[package]
name = "multipart-parser"
version = "0.1.0"
edition = "2021"
authors = ["Na'aman Hirschfeld <nhirschfeld@gmail.com>"]

[dependencies]
encoding_rs = "0.8.31"
lazy_static = "1.4.0"
percent-encoding = "2.2.0"
regex = "1.7.0"
serde_json = "1.0.91"
